[project]
name = "pdm_sqlite_debug"
requires-python = ">=3.11"
license = {text = "MIT"}
version = "0.0.1"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

dependencies = [
    "jbpy>=0.5.1, <0.6",
    "lxml>=5.1.0",
    "numpy>=1.25.0",
    "shapely>=2.0.2",
    "nox>=2024.3.2",
    "sphinx>=7.2.6,<9",
    "numpydoc>=1.7.0",
    "sphinx-rtd-theme>=2.0.0",
    "sphinxcontrib-autoprogram>=0.1.9",
    "xmlschema>=4.0.1",
    "ruff>=0.3.0",
    "mypy>=1.8.0",
    "aiohttp>=3.11",
    "pytest>=7.4.4",
    "smart_open[http]>=7.1.0",
    "scipy>=1.12.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true