# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on: push

jobs:
  current_env_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: checkout
      uses: actions/checkout@v6
      with:
        lfs: false  # Save GitHub LFS bandwidth
    - name: Setup PDM and Python
      id: setup
      uses: pdm-project/setup-pdm@v4
      with:
        python-version: 3.14
        version: 2.26.2
    - name: Dump setup context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.setup.outputs) }}
      run: echo "$STEPS_CONTEXT"
    - name: inspect windows
      if: runner.os == 'Windows'
      run: |
        & C:\Users\runneradmin\AppData\Roaming\pdm\venv\Scripts\activate.ps1
        pip list
    - name: inspect linux
      if: runner.os == 'Linux'
      run: |
        source /home/runner/.local/share/pdm/venv/bin/activate
        pip list
    - name: install
      run: |
        pdm info && pdm info --env
        pdm lock
        pdm sync
